pipeline:
  build:
    image: ruby:2.5.3
    commands:
      - gem install bundler -v 1.17.1
      - bundle install
      - bundle exec rspec spec
    when:
      - image: plugins/github-comment
        type: create
        contains:
          - test this please
